server:
  port: 8443
spring:
  application:
    name: gateway.http3
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: https://projectreactor.io
        predicates:
        - Path=/
#  ssl:
#    bundle:
#      jks:
#        server-http3:
#          key:
#            alias: http3
#          keystore:
#            location: ...
#            password: ...
#            type: ...
#        client-http3:
#        ...